export const techIcons = {
  'Vue.js': 'logos:vue',
  Vue: 'logos:vue',
  'Vue 3': 'logos:vue',
  Laravel: 'logos:laravel',
  Python: 'logos:python',
  FastAPI: 'simple-icons:fastapi',
  Docker: 'logos:docker-icon',
  React: 'logos:react',
  'Next.js': 'logos:nextjs-icon',
  PostgreSQL: 'logos:postgresql',
  MySQL: 'logos:mysql',
  Redis: 'logos:redis',
  MongoDB: 'logos:mongodb',
  OAuth2: 'mdi:shield-lock',
  JWT: 'mdi:key',
  Flutter: 'logos:flutter',
  Go: 'logos:go',
  'OpenAI API': 'simple-icons:openai',
  'Tailwind CSS': 'logos:tailwindcss-icon',
  ESP32: 'mdi:chip',
  MQTT: 'mdi:access-point-network',
  Filament: 'mdi:view-dashboard',
  JavaScript: 'logos:javascript',
  TypeScript: 'logos:typescript-icon',
  Nodejs: 'logos:nodejs-icon',
  'Node.js': 'logos:nodejs-icon',
  GraphQL: 'logos:graphql',
  Git: 'logos:git-icon',
  Nginx: 'logos:nginx',
  Linux: 'logos:linux-tux',
  AWS: 'logos:aws',
  Firebase: 'logos:firebase',
  Supabase: 'logos:supabase-icon',
  Arduino: 'mdi:chip',
  'Raspberry Pi': 'mdi:raspberry-pi',
}
